window.quotes = [
  "Success begins where excuses end.",
  "Small steps every day create big results.",
  "Discipline beats motivation.",
  "Believe in yourself and keep moving.",
  "Dreams work when you do.",
  "Every great journey begins with one small step.",
  "Believe in yourself even when no one else does.",
  "Success comes to those who never give up.",
  "Your future is created by what you do today.",
  "Stay focused and trust the process.",
  "Hard work always beats excuses.",
  "Small progress is still progress.",
  "Turn your dreams into goals and your goals into reality.",
  "Every challenge is an opportunity to grow.",
  "Great things take time, so stay patient.",
  "Confidence grows through action.",
  "Keep moving forward no matter how slow.",
  "Winners never stop learning.",
  "Be stronger than your strongest excuse.",
  "Success starts with self-belief.",
  "Every sunrise is a new chance to succeed.",
  "Make today better than yesterday.",
  "Your mindset shapes your future.",
  "Never underestimate the power of consistency.",
  "The best investment is investing in yourself.",
  "Life is a journey, not a race.",
  "Happiness begins with gratitude.",
  "Every day is a fresh start.",
  "Life rewards those who stay consistent.",
  "Your attitude determines your direction.",
  "Kindness never goes out of style.",
  "Learn from yesterday, live for today.",
  "A positive mind creates a positive life.",
  "Every moment is a chance to begin again.",
  "Life becomes better when you become better.",
  "Stay humble and work hard.",
  "Peace comes from within.",
  "Your story is still being written.",
  "Focus on progress, not perfection.",
  "Every experience teaches a lesson.",
  "Smile more, worry less.",
  "Good things take time.",
  "Live with purpose and passion.",
  "Never stop believing in yourself.",
  "Make every day meaningful.",
  "Success is earned, never given.",
  "Work hard in silence, let success make the noise.",
  "Big dreams require big efforts.",
  "Every master was once a beginner.",
  "Stay committed to your goals."
];
